---
apiVersion: v1
kind: Pod
metadata:
  name: random-number-pod
spec:
  containers:
  - name: service
    image: hydrokhoos/random-num-service:latest
    volumeMounts:
    - name: shared-storage
      mountPath: /shared
    command: ['python3', '/service.py']
  - name: sidecar
    image: hydrokhoos/random-num-sidecar:latest
    volumeMounts:
    - name: shared-storage
      mountPath: /shared
    env:
    - name: SERVICE_NAME
      value: /randomNum
    command: ['sh', '-c','nfd-start 2> /nfd.log; python3 /sidecar.py']
  initContainers:
  - name: volume-init
    image: busybox
    volumeMounts:
    - name: shared-storage
      mountPath: /shared
    command: ['sh', '-c', 'if [ -f /shared/semaphore ]; then rm /shared/semaphore; fi; if [ -f /shared/data ]; then rm /shared/data; fi;']

  volumes:
  - name: shared-storage
    emptyDir: {}
